services:
  backend:
    build: .
    container_name: rating-backend
    expose:
      - "8080"
    environment:
      - DB_HOST=rating-app-db.c12qgu806226.us-east-2.rds.amazonaws.com
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=SuperSecretPass123!
      - JWT_SECRET_BASE64=m6RcrMovSQCKAT9nyxlfdkXU75fsOeiAObPS3sxZ1vsbEwvHNIAbRsFJ7BEp6OC2eWf4mUCoGsTiF6/frbk+YA==
      - ALLOWED_ORIGINS=http://gurugram.tech
    restart: always

  frontend:
    build: ./frontend
    container_name: rating-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always